# Generated by Django 5.0.1 on 2024-01-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
